version: '3.8'

services:
  sidorov-web:
    # image: ghcr.io/toptuk/sidorov_ru:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-gpt-proxy
    restart: always

networks:
  default:
    name: pmi_network